name: containers
on: [push, pull_request]

jobs:
  containers:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          environment-file: conda/containers.yaml
          channels: conda-forge,nodefaults
          activate-environment: waveapp
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: Create environment variables file
        run: |
          export HOST_UID=$(id -u)
          export HOST_GID=$(id -g)
          envsubst < .env.tpl > .env

      - name: build images
        run: make containers-build

      - name: start service
        run: make containers-start

      - name: health check
        run: make containers-wait SERVICE=waveapp

      - name: stop services
        run: make containers-stop
